openapi: 3.1.0
info:
  title: SlimBuddy Backend API
  description: API for logging meals, weight, exercise, measurements, updating settings and food values for SlimBuddy users.
  version: 1.0.1
servers:
  - url: https://slimbuddy-backend-production.up.railway.app

paths:
  /api/ping:
    get:
      summary: Ping the API
      description: Verifies that the backend API is running.
      operationId: ping
      responses:
        "200":
          description: API is alive
  /api/log_meal:
    post:
      summary: Log a meal
      operationId: logMeal
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - meal_description
                - syns
              properties:
                user_id:
                  type: string
                meal_description:
                  type: string
                syns:
                  type: number
                meal_type:
                  type: string
                healthy_extra_a_used:
                  type: boolean
                healthy_extra_b_used:
                  type: boolean
                notes:
                  type: string
                date:
                  type: string
      responses:
        "200":
          description: Meal logged
  /api/log_weight:
    post:
      summary: Log a user's weight
      operationId: logWeight
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - weight
                - date
              properties:
                user_id:
                  type: string
                weight:
                  type: number
                date:
                  type: string
      responses:
        "200":
          description: Weight logged
  /api/log_exercise:
    post:
      summary: Log exercise activity
      operationId: logExercise
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - exercise_type
                - duration_minutes
              properties:
                user_id:
                  type: string
                exercise_type:
                  type: string
                duration_minutes:
                  type: number
                notes:
                  type: string
                date:
                  type: string
      responses:
        "200":
          description: Exercise logged
  /api/log_measurements:
    post:
      summary: Log body measurements
      operationId: logMeasurements
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - date
              properties:
                user_id:
                  type: string
                chest:
                  type: number
                waist:
                  type: number
                hips:
                  type: number
                date:
                  type: string
      responses:
        "200":
          description: Measurements logged
  /api/user_goals:
    post:
      summary: Log or update user goals
      operationId: userGoals
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                target_weight:
                  type: number
                weekly_goal:
                  type: string
                maintenance_mode_enabled:
                  type: boolean
      responses:
        "200":
          description: Goals updated
  /api/update_user_settings:
    patch:
      summary: Update user settings
      operationId: updateUserSettings
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                preferred_name:
                  type: string
                goal_type:
                  type: string
                starting_weight:
                  type: number
                preferred_weight_unit:
                  type: string
                tone:
                  type: string
                diet_preference:
                  type: string
                food_allergies:
                  type: string
                food_dislikes:
                  type: string
                typical_day:
                  type: string
                healthy_extra_a:
                  type: string
                healthy_extra_b:
                  type: string
                syn_limit:
                  type: number
                target_weight:
                  type: number
                maintenance_mode_enabled:
                  type: boolean
      responses:
        "200":
          description: User settings updated
  /api/update_food_value:
    post:
      summary: Update or override a food's Syn value
      operationId: updateFoodValue
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - food_name
                - syn_value
              properties:
                user_id:
                  type: string
                food_name:
                  type: string
                syn_value:
                  type: number
                is_healthy_extra_b:
                  type: boolean
                notes:
                  type: string
      responses:
        "200":
          description: Food value updated
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Dummy:
      type: object
      description: Placeholder schema (required for OpenAI importer)

