openapi: 3.1.0
info:
  title: SlimBuddy API
  version: 1.0.0
  description: API specification for SlimBuddy backend services.

servers:
  - url: https://slimbuddy-backend-production.up.railway.app

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas: {}  # ✅ This prevents the "schemas subsection is not an object" error

paths:
  /api/ping:
    get:
      summary: Health check
      operationId: getPingStatus
      security: []  # No auth required
      responses:
        '200':
          description: API is alive

  /api/log_weight:
    post:
      summary: Log a weight entry
      operationId: logWeight
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                weight:
                  type: number
                  example: 75.5
                date:
                  type: string
                  example: 2024-09-04
                unit:
                  type: string
                  example: kg
                notes:
                  type: string
      responses:
        '200':
          description: Weight logged successfully

  /api/log_measurements:
    post:
      summary: Log body measurements
      operationId: logMeasurements
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                  example: 2024-09-04
                bust:
                  type: number
                waist:
                  type: number
                hips:
                  type: number
                neck:
                  type: number
                arm:
                  type: number
                under_bust:
                  type: number
                thighs:
                  type: number
                knees:
                  type: number
                ankles:
                  type: number
                notes:
                  type: string
      responses:
        '200':
          description: Measurements logged successfully

  /api/log_meal:
    post:
      summary: Log a meal
      operationId: logMeal
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Meal logged successfully

  /api/log_exercise:
    post:
      summary: Log exercise
      operationId: logExercise
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Exercise logged successfully

  /api/weight_graph:
    get:
      summary: Get weight graph data
      operationId: getWeightGraph
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Weight graph data retrieved

  /api/user_profile:
    get:
      summary: Get user profile
      operationId: getUserProfile
      security:
        - BearerAuth: []
      responses:
        '200':
          description: User profile retrieved

  /api/user_goals:
    get:
      summary: Get user goals
      operationId: getUserGoals
      security:
        - BearerAuth: []
      responses:
        '200':
          description: User goals retrieved

  /api/update_user_settings:
    put:
      summary: Update user settings
      operationId: updateUserSettings
      security:
        - BearerAuth: []
      responses:
        '200':
          description: User settings updated

  /api/update_food_value:
    put:
      summary: Update food value
      operationId: updateFoodValue
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Food value updated
