openapi: 3.1.0
info:
  title: SlimBuddy API (GPT Import - UI-auth)
  version: 1.0.0
  description: >
    Actions expect an "Authorization" header (configured in GPT UI as API Key).
    Users must paste: "Bearer <their token>".

servers:
  - url: https://slimbuddy-backend-production.up.railway.app

components:
  schemas:
    LogWeightRequest:
      type: object
      additionalProperties: false
      properties:
        date: { type: string, description: "YYYY-MM-DD or UK format; server normalizes" }
        weight: { type: number }
        unit: { type: string, enum: [kg, lbs, st_lbs] }
        stones: { type: number, nullable: true, description: "If unit=st_lbs" }
        pounds: { type: number, nullable: true, description: "If unit=st_lbs" }
        notes: { type: string, nullable: true }
      required: [unit]

paths:
  /api/ping:
    get:
      operationId: ping
      summary: Health check
      responses:
        '200': { description: OK }

  /api/auth_echo:
    get:
      operationId: authEcho
      summary: Echo authenticated user (debug)
      responses:
        '200': { description: OK }
        '401': { description: Unauthorized }

  /api/log_weight:
    post:
      operationId: logWeight
      summary: Log a weight entry
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/LogWeightRequest' }
      responses:
        '200': { description: OK }
        '400': { description: Bad request }
        '401': { description: Unauthorized }
        '500': { description: Server error }
