openapi: 3.1.1
info:
  title: SlimBuddy API (Minimal Test)
  version: 1.0.0
  description: Minimal spec to validate GPT import + bearerAuth

servers:
  - url: https://slimbuddy-backend-production.up.railway.app

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    SimpleOk:
      type: object
      properties:
        ok: { type: boolean }
        message: { type: string }
    EchoResponse:
      type: object
      properties:
        ok: { type: boolean }
        user:
          type: object
          properties:
            id: { type: string }
            email: { type: string, nullable: true }
    LogWeightRequest:
      type: object
      additionalProperties: false
      properties:
        date: { type: string, description: "YYYY-MM-DD or human-friendly; server normalizes" }
        weight: { type: number, description: "If unit=kg or lbs" }
        unit: { type: string, enum: [kg, lbs, st_lbs] }
        stones: { type: number, description: "If unit=st_lbs" }
        pounds: { type: number, description: "If unit=st_lbs (optional)" }
        notes: { type: string }
      required: [unit]

paths:
  /api/ping:
    get:
      summary: Health check
      operationId: ping
      responses:
        '200':
          description: Backend OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleOk'

  /api/auth_echo:
    get:
      summary: Verify auth and echo user
      operationId: authEcho
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Echoed user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EchoResponse'
        '401':
          description: Unauthorized

  /api/log_weight:
    post:
      summary: Log a weight entry
      operationId: logWeight
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogWeightRequest'
      responses:
        '200':
          description: Weight logged
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleOk'
        '400': { description: Bad request }
        '401': { description: Unauthorized }
        '500': { description: Server error }
