openapi: 3.1.1
info:
  title: SlimBuddy API (GPT Import - Minimal)
  version: 1.0.0
servers:
  - url: https://slimbuddy-backend-production.up.railway.app

paths:
  /api/ping:
    get:
      operationId: ping
      summary: Health check
      responses:
        '200':
          description: OK

  /api/auth_echo:
    get:
      operationId: authEcho
      summary: Echo authenticated user (debug)
      parameters:
        - name: Authorization
          in: header
          required: true
          description: "Paste: Bearer <your SlimBuddy token>"
          schema:
            type: string
          x-openai-is-secret: true
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized

  /api/log_weight:
    post:
      operationId: logWeight
      summary: Log a weight entry
      parameters:
        - name: Authorization
          in: header
          required: true
          description: "Paste: Bearer <your SlimBuddy token>"
          schema:
            type: string
          x-openai-is-secret: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                date:
                  type: string
                  description: "YYYY-MM-DD or UK format; server normalizes"
                weight:
                  type: number
                unit:
                  type: string
                  enum: [kg, lbs, st_lbs]
                stones:
                  type: number
                  description: "If unit=st_lbs"
                pounds:
                  type: number
                  description: "If unit=st_lbs (optional)"
                notes:
                  type: string
              required: [unit]
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Server error
