openapi: 3.1.0
info:
  title: SlimBuddy API (GPT Import - Minimal)
  version: 1.0.0
  description: |
    Paste your token when prompted — include "Bearer ", for example:
    Bearer eyJhbGciOiJIUzI1NiIs...

servers:
  - url: https://slimbuddy-backend-production.up.railway.app

components:
  schemas: {}
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: "Paste: Bearer <your SlimBuddy token>"
      x-openai-is-secret: true

security:
  - ApiKeyAuth: []  # apply Authorization to all paths by default

paths:
  /api/ping:
    get:
      operationId: ping
      summary: Health check
      security: []      # ping does not require auth
      responses:
        '200': { description: OK }

  /api/auth_echo:
    get:
      operationId: authEcho
      summary: Echo authenticated user (debug)
      responses:
        '200': { description: OK }
        '401': { description: Unauthorized }

  /api/log_weight:
    post:
      operationId: logWeight
      summary: Log a weight entry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                date:
                  type: string
                  description: "YYYY-MM-DD or UK format; server normalizes"
                weight:
                  type: number
                unit:
                  type: string
                  enum: [kg, lbs, st_lbs]
                stones:
                  type: number
                  description: "If unit=st_lbs"
                pounds:
                  type: number
                  description: "If unit=st_lbs (optional)"
                notes:
                  type: string
              required: [unit]
      responses:
        '200': { description: OK }
        '400': { description: Bad request }
        '401': { description: Unauthorized }
        '500': { description: Server error }
